kenjohnson03/DelegationStation

DelegationSharedLibrary/ExtensionHelper.cs, DelegationStation/DelegationStation.csproj, DelegationStation/appsettings.json, DelegationStationTests/DelegationStationTests.csproj, UpdateDevices/UpdateDevices.cs
Updates to UpdateDevices.  Started working similar changes to IntuneEnrollment function app, but still in progress and wanted to get these in first.
=> Updating logic to retrieve class/method name for logging.

DelegationSharedLibrary/DelegationSharedLibrary.csproj, DelegationStation/DelegationStation.csproj, DelegationStation/Pages/DevicesBulkAction.razor, DelegationStation/Pages/TagEdit.razor, DelegationStationTests/DelegationStationTests.csproj, DelegationStationTests/Pages/TagEditTest.cs, IntuneEnrollment/IntuneEnrollment.csproj
Submitting PR since we should be able to use it to test deployment.
Login works as does most of the functionality.
However, Tag Edit has failing Unit Tests and is crashing application.
=> Update webapp to .NET6

README.md, UpdateDevices/UpdateDevices.cs
Added logic to map AzureADDeviceID to graph device object ID to doupdate actions.
Updated README.md to add additional Graph Permissions needed.
=> Fix issue updating groups,AUs and attributes.

DelegationStation/appsettings.json, README.md, UpdateDevices/local.settings.json.template
Added new/changed settings to appsettings.json and local.settings.json.template.
Updated README.md with additional details and did some reorganization.
=> Cleanup readme configs

DelegationStation/Pages/Devices.razor
=> Task6778:  Fixing bug where AddedBy was not set correctly on Devices

DelegationSharedLibrary/Models/Graph/ManagedDevice.cs, DelegationSharedLibrary/Models/Role.cs, DelegationSharedLibrary/Models/RoleDelegation.cs, DelegationStation/API/BulkDeviceController.cs, DelegationStation/DelegationStation.csproj, DelegationStation/Models/ClaimsManager.cs, DelegationStation/Program.cs, DelegationStation/Services/DeviceDBService.cs, DelegationStation/Services/DeviceTagDBService.cs, DelegationStation/Services/RoleDBService.cs, DelegationStationTests/DelegationStationTests.csproj, DelegationStationTests/Pages/LoginDisplayTest.cs, DelegationStationTests/Pages/RoleTest.cs, DelegationStationTests/Pages/TagEditTest.cs, DelegationStationTests/Pages/TagTest.cs, IntuneEnrollment/IntuneEnrollment.csproj, UpdateDevices/Program.cs, UpdateDevices/UpdateDevices.csproj
Updated libraries to latest versions.
Removed unnecessary usings.
=> March: Dependency Updates

DelegationStation/Pages/Tags.razor, DelegationStation/Services/DeviceTagDBService.cs
Added logic to retrieve tags a page at a time and added pagination buttons to screen.
=> Task6818:  Adding basic paging to Tags screen

UpdateDevices/UpdateDevices.cs
=> Task 8747:  Removing use of argument to see if it resolves error with

UpdateDevices/UpdateDevices.cs
Updating code to pull value from config OR if not provided defaults to 30.
=> Feature 9662:  Make initial run days configurable.

.github/workflows/dotnet.yml, DelegationStation.sln, WhiteSpaceCleaner/LoggerExtensions.cs, WhiteSpaceCleaner/Program.cs, WhiteSpaceCleaner/Settings.job, WhiteSpaceCleaner/WhiteSpaceCleaner.cs, WhiteSpaceCleaner/WhiteSpaceCleaner.csproj
Rewrote as a console app that can be built and uploaded to the DS webapp as a web job.
=> Migrate WhiteSpaceCleaner from Function App to WebApp

DelegationStation/API/BulkDeviceController.cs, DelegationStation/Pages/DevicesBulkAction.razor
Switched parsing in file upload logic to use Regex to split if quoted commas are present.
Updated download logic to wrap any fields containing commas with quotes.
=> Fixing bulk update/download issues related to commas

.gitignore
Added entry to ignore service dependency configuration files used for publishing from Visual studio.
=> Updating git commit to ignore local VS publish settings

DelegationStation/DelegationStation.csproj, DelegationStation/Services/GraphService.cs, DelegationStationTests/DelegationStationTests.csproj, IntuneEnrollment/IntuneEnrollment.csproj, UpdateDevices/Extensions/LoggerExtensions.cs, UpdateDevices/Services/CosmosDbService.cs, UpdateDevices/UpdateDevices.cs, UpdateDevices/UpdateDevices.csproj, WhiteSpaceCleaner/WhiteSpaceCleaner.csproj
Updated libraries and updating some string functions which were no longer supported as is.
=> November Library Updates and related updates.

DelegationStation.sln, DelegationStation/Services/DeviceDBService.cs, RemoveCaseSensitiveDuplicates/LoggerExtensions.cs, RemoveCaseSensitiveDuplicates/Models/Duplicate.cs, RemoveCaseSensitiveDuplicates/Program.cs, RemoveCaseSensitiveDuplicates/RemoveCaseSensitiveDuplicates.csproj, RemoveCaseSensitiveDuplicates/RemoveDupes.cs, UpdateDevices/Services/CosmosDbService.cs
Includes:
- Updating function app to do case-insensitive comparison
- Updated duplicate checking on device add 
- Created webjob to clean up what are now "duplicates" when allowing for case-insensitivity
- Webjob will also check for any duplicates between tags and log them (since if there are any, it will require manual intervention)
Sample output from webjob:
```
[12/17/2024 23:57:20 > 5cca01: INFO]       [INFO] (RemoveDupes.RunAsync) Case-Insensitive Duplicate Removal Job starting....
[12/17/2024 23:57:20 > 5cca01: INFO] info: RemoveCaseSensitiveDuplicates.RemoveDupes[0]
...
[12/17/2024 23:57:27 > 5cca01: INFO] info: RemoveCaseSensitiveDuplicates.RemoveDupes[0]
[12/17/2024 23:57:27 > 5cca01: INFO]       [INFO] (RemoveDupes.CleanupAsync) Found 3 duplicates when case ignored: 'duplicate1' …
```
=> Feature:  Case-Insensitve Matching

DelegationStation/DelegationStation.csproj, DelegationStationTests/DelegationStationTests.csproj, IntuneEnrollment/IntuneEnrollment.csproj, RemoveCaseSensitiveDuplicates/RemoveCaseSensitiveDuplicates.csproj, UpdateDevices/UpdateDevices.csproj
=> Jan 6 - straightforward library updates

CorporateIdentifierSyncs/AddNewDevices.cs, CorporateIdentifierSyncs/ConfirmSync.cs, CorporateIdentifierSyncs/DeviceDeletion.cs, README.md
AddDevices function:  if not set or set to false, will return immediately
ConfirmSync function:  if not set or set to false, will return immediately
DeleteDevices function:  if set to false, will not attempt to delete device from CorpIDs
=> Add flag to enable CorpID Sync

DelegationSharedLibrary/DelegationSharedLibrary.csproj, DelegationStation/DelegationStation.csproj, DelegationStationTests/DelegationStationTests.csproj, IntuneEnrollment/IntuneEnrollment.csproj, RemoveCaseSensitiveDuplicates/RemoveCaseSensitiveDuplicates.csproj, UpdateDevices/UpdateDevices.csproj
Updating dependency libraries to latest versions.  No code changes required.
=> February Library Updates

DelegationSharedLibrary/Models/Straggler.cs, README.md, UpdateDevices/Cleanup.cs, UpdateDevices/Interfaces/ICosmosDbService.cs, UpdateDevices/Interfaces/IGraphServices.cs, UpdateDevices/Program.cs, UpdateDevices/Services/CosmosDbService.cs, UpdateDevices/Services/GraphService.cs, UpdateDevices/StragglerHandler.cs, UpdateDevices/UpdateDevices.cs, UpdateDevices/local.settings.json.template
Includes:
* Refactoring graph code into service, which also allows for shared code.
* Implement new Stragger Handler function
* Implemented new Cleanup function
=> Implement "Stragger Handler" function

UpdateDevices/StragglerHandler.cs, UpdateDevices/UpdateDevices.cs
Updated logic related to UPN regex check to allow devices with null UPNs to be processed.
(Appears to be related to bulk enrollment.)
=> Updated logging in both functions to handle null or empty string in UPN

tools/speedUpOldStraggers
Controlling stored procedure used during last deployment to advance stragglers to state where they will get picked up by Straggler Handler.
=> Control stored procedure

README.md, scripts/enableCosmosMI.sh.template
* Updated README
* Fixed issues with checked-in version of dev setup script
=> Additional updates related to Cosmos Managed Identity

CorporateIdentifierSyncs/AddNewDevices.cs, CorporateIdentifierSyncs/ConfirmSync.cs, DelegationSharedLibrary/Enums/DeviceOS.cs, DelegationStation/Pages/Devices.razor, DelegationStation/Pages/DevicesBulkAction.razor.cs
and treat them as Windows devices.
=> Modified DeviceOS enum to include Unknown for use with existing hosts

DelegationSharedLibrary/DelegationSharedLibrary.csproj, DelegationStation/DelegationStation.csproj, DelegationStationTests/DelegationStationTests.csproj, IntuneEnrollment/IntuneEnrollment.csproj, RemoveCaseSensitiveDuplicates/RemoveCaseSensitiveDuplicates.csproj, UpdateDevices/UpdateDevices.csproj
Including assignees for awareness, but since there are no code changes to review will go ahead and merge following successful build.
=> US25939:  July library updates
